[package]
name = "rectangles"
version = "0.1.0"
authors = ["Jhon Rocha <jhonantans.moraes@bairesdev.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
